<#
.SYNOPSIS
    Builds Setup.exe -- a single self-contained installer for System-Setup.
.DESCRIPTION
    1. Bundles all scripts + data files into a self-extracting PowerShell script.
    2. Compiles that script into Setup.exe using ps2exe.
    3. The .exe auto-elevates, extracts to a temp folder, launches Setup.ps1,
       and cleans up after itself.

    Run this from the Windows\ folder:
        .\Build-Exe.ps1

    Output: ..\dist\Setup.exe
.NOTES
    Requires: Install-Module ps2exe -Scope CurrentUser
    Or:       dotnet tool install --global ps2exe
#>

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$DistDir   = Join-Path (Split-Path $ScriptDir) 'dist'
$TempBuild = Join-Path $env:TEMP 'SystemSetup-Build'

# Clean previous build
if (Test-Path $TempBuild) { Remove-Item $TempBuild -Recurse -Force }
New-Item -ItemType Directory -Path $TempBuild -Force | Out-Null
if (-not (Test-Path $DistDir)) { New-Item -ItemType Directory -Path $DistDir -Force | Out-Null }

Write-Host "Building Setup.exe..." -ForegroundColor Cyan

# --- Step 1: Ensure ps2exe is available ---
if (-not (Get-Command Invoke-ps2exe -ErrorAction SilentlyContinue)) {
    if (-not (Get-Module ps2exe -ListAvailable -ErrorAction SilentlyContinue)) {
        Write-Host "Installing ps2exe module..." -ForegroundColor Yellow
        Install-Module ps2exe -Scope CurrentUser -Force
    }
    Import-Module ps2exe
}

# --- Step 2: Collect all files to embed ---
$filesToEmbed = @(
    'Setup.ps1',
    'Setup-UI.ps1',
    'restore.ps1',
    'Enable-WindowsFeatures.ps1',
    'bootstrap-dev.sh',
    'Sign-Scripts.ps1',
    'Setup.cmd',
    'winget-packages.json',
    'vscode-extensions.txt',
    'zshrc-template',
    'p10k-template'
)

# zsh-gitbash.tar.gz is binary -- embed as base64
$binaryFiles = @(
    'zsh-gitbash.tar.gz'
)

Write-Host "  Embedding files..." -ForegroundColor DarkGray

# Build the embedded data as a PowerShell hashtable literal
$embedCode = @()
$embedCode += '# --- Embedded files (auto-generated by Build-Exe.ps1) ---'
$embedCode += '$embeddedFiles = @{'

foreach ($f in $filesToEmbed) {
    $path = Join-Path $ScriptDir $f
    if (-not (Test-Path $path)) {
        Write-Warning "  Skipping missing file: $f"
        continue
    }
    $content = [System.IO.File]::ReadAllText($path)
    # Escape single quotes for embedding in a PowerShell here-string
    $escaped = $content -replace "'", "''"
    $embedCode += "    '$f' = @'"
    $embedCode += $escaped
    $embedCode += "'@"
    Write-Host "    + $f" -ForegroundColor DarkGray
}

foreach ($f in $binaryFiles) {
    $path = Join-Path $ScriptDir $f
    if (-not (Test-Path $path)) {
        Write-Warning "  Skipping missing binary: $f"
        continue
    }
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $b64 = [Convert]::ToBase64String($bytes)
    $embedCode += "    '$f' = '[BASE64]$b64'"
    Write-Host "    + $f ($('{0:N1} MB' -f ($bytes.Length / 1MB)) base64)" -ForegroundColor DarkGray
}

$embedCode += '}'
$embedCode += ''

# --- Step 3: Build the launcher script ---
$launcherCode = @'
<#
    System-Setup -- Self-Extracting Installer
    This file was generated by Build-Exe.ps1. Do not edit manually.
#>

# --- Auto-elevate ---
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    $argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', "`"$($MyInvocation.MyCommand.Definition)`"")
    try {
        Start-Process -FilePath 'powershell.exe' -ArgumentList $argList -Verb RunAs -Wait
        exit 0
    }
    catch {
        Write-Error "Failed to elevate: $_"
        exit 1
    }
}

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force -ErrorAction SilentlyContinue

# --- Extract to temp folder ---
$extractDir = Join-Path $env:TEMP ('SystemSetup-' + [guid]::NewGuid().ToString('N').Substring(0,8))
New-Item -ItemType Directory -Path $extractDir -Force | Out-Null

Write-Host "Extracting setup files..." -ForegroundColor Cyan

foreach ($name in $embeddedFiles.Keys) {
    $outPath = Join-Path $extractDir $name
    $content = $embeddedFiles[$name]

    if ($content -is [string] -and $content.StartsWith('[BASE64]')) {
        # Binary file -- decode base64
        $b64 = $content.Substring(8)
        $bytes = [Convert]::FromBase64String($b64)
        [System.IO.File]::WriteAllBytes($outPath, $bytes)
    }
    else {
        # Text file
        [System.IO.File]::WriteAllText($outPath, $content)
    }
}

Write-Host "  Extracted to: $extractDir" -ForegroundColor DarkGray

# --- Run Setup.ps1 from the extracted folder ---
$setupScript = Join-Path $extractDir 'Setup.ps1'
try {
    & $setupScript @args
}
finally {
    # --- Cleanup ---
    Write-Host ""
    Write-Host "Cleaning up temp files..." -ForegroundColor DarkGray
    Start-Sleep -Milliseconds 500
    Remove-Item $extractDir -Recurse -Force -ErrorAction SilentlyContinue
}
'@

# --- Step 4: Combine embedded data + launcher into one script ---
$combinedScript = Join-Path $TempBuild 'Setup-Combined.ps1'
$allCode = ($embedCode -join "`n") + "`n`n" + $launcherCode
[System.IO.File]::WriteAllText($combinedScript, $allCode)

Write-Host "  Combined script: $('{0:N0} KB' -f ((Get-Item $combinedScript).Length / 1KB))" -ForegroundColor DarkGray

# --- Step 5: Compile to .exe ---
$exePath = Join-Path $DistDir 'Setup.exe'

Write-Host "  Compiling to .exe..." -ForegroundColor Cyan

$ps2exeParams = @{
    inputFile  = $combinedScript
    outputFile = $exePath
    noConsole  = $false          # keep console for output
    requireAdmin = $true         # manifest: requires elevation
    title      = 'System-Setup'
    description = 'Windows Dev Machine Setup'
    company    = 'System-Setup'
    version    = '1.0.0.0'
    copyright  = 'MIT License'
}

Invoke-ps2exe @ps2exeParams

if (Test-Path $exePath) {
    $size = (Get-Item $exePath).Length
    Write-Host ""
    Write-Host "  Build successful!" -ForegroundColor Green
    Write-Host "  Output: $exePath" -ForegroundColor Green
    Write-Host "  Size:   $('{0:N1} MB' -f ($size / 1MB))" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Distribute this single file. Users just double-click it." -ForegroundColor DarkGray
}
else {
    Write-Error "Build failed -- no .exe produced."
    exit 1
}

# Cleanup build temp
Remove-Item $TempBuild -Recurse -Force -ErrorAction SilentlyContinue
