<#
.SYNOPSIS
    Builds Setup.exe -- a single self-contained installer.
.DESCRIPTION
    Embeds all files as base64 strings (no here-strings -- avoids PS parse
    issues with special characters). Compiles into Setup.exe via ps2exe.

    Run from the Windows\ folder:  .\Build-Exe.ps1
    Output: ..\dist\Setup.exe
#>

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$DistDir   = Join-Path (Split-Path $ScriptDir) 'dist'
$TempBuild = Join-Path $env:TEMP 'SystemSetup-Build'

if (Test-Path $TempBuild) { Remove-Item $TempBuild -Recurse -Force }
New-Item -ItemType Directory -Path $TempBuild -Force | Out-Null
if (-not (Test-Path $DistDir)) { New-Item -ItemType Directory -Path $DistDir -Force | Out-Null }

Write-Host "Building Setup.exe..." -ForegroundColor Cyan

# --- Ensure ps2exe ---
if (-not (Get-Command Invoke-ps2exe -ErrorAction SilentlyContinue)) {
    if (-not (Get-Module ps2exe -ListAvailable -ErrorAction SilentlyContinue)) {
        Write-Host "Installing ps2exe..." -ForegroundColor Yellow
        Install-Module ps2exe -Scope CurrentUser -Force -Repository PSGallery
    }
    Import-Module ps2exe
}

# --- Files to embed (ALL as base64 -- safe, no parse issues) ---
$allFiles = @(
    'Setup.ps1', 'Setup-UI.ps1', 'restore.ps1', 'Enable-WindowsFeatures.ps1',
    'bootstrap-dev.sh', 'Sign-Scripts.ps1', 'Setup.cmd',
    'winget-packages.json', 'vscode-extensions.txt',
    'zshrc-template', 'p10k-template', 'zsh-gitbash.tar.gz'
)

Write-Host "  Embedding files as base64..." -ForegroundColor DarkGray

# Build a script that declares a hashtable of name=>base64
$sb = [System.Text.StringBuilder]::new(4MB)
[void]$sb.AppendLine('# Auto-generated by Build-Exe.ps1. Do not edit.')
[void]$sb.AppendLine('$fileData = @{}')

foreach ($f in $allFiles) {
    $path = Join-Path $ScriptDir $f
    if (-not (Test-Path $path)) {
        Write-Warning "  Skipping missing: $f"
        continue
    }
    $bytes = [System.IO.File]::ReadAllBytes($path)
    $b64   = [Convert]::ToBase64String($bytes)
    # Each file is one safe line: $fileData['name'] = 'base64...'
    [void]$sb.AppendLine("`$fileData['$f'] = '$b64'")
    $sizeMB = $bytes.Length / 1MB
    if ($sizeMB -gt 0.1) {
        Write-Host ("    + {0} ({1:N1} MB)" -f $f, $sizeMB) -ForegroundColor DarkGray
    }
    else {
        Write-Host "    + $f" -ForegroundColor DarkGray
    }
}

[void]$sb.AppendLine('')

# --- Launcher code ---
$launcher = @'

# ===== System-Setup Self-Extracting Installer =====
# Elevation is handled by the exe manifest (requireAdmin=true).

$ErrorActionPreference = 'Stop'

# Log to a file so we can debug if the window closes too fast
$logFile = Join-Path $env:TEMP 'SystemSetup-installer.log'

function Log($msg) {
    $ts = Get-Date -Format 'HH:mm:ss'
    $line = "[$ts] $msg"
    Add-Content -Path $logFile -Value $line -ErrorAction SilentlyContinue
    Write-Host $line
}

try {
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force -ErrorAction SilentlyContinue
    $host.UI.RawUI.WindowTitle = 'System-Setup Installer'

    Log '============================================='
    Log ' System-Setup Installer'
    Log '============================================='
    Log ''

    # --- Extract ---
    $extractDir = Join-Path $env:TEMP ('SystemSetup-' + (Get-Date -Format 'yyyyMMddHHmmss'))
    New-Item -ItemType Directory -Path $extractDir -Force | Out-Null
    Log "Extracting to: $extractDir"

    $count = 0
    foreach ($name in $fileData.Keys) {
        $outPath = Join-Path $extractDir $name
        $bytes = [Convert]::FromBase64String($fileData[$name])
        [System.IO.File]::WriteAllBytes($outPath, $bytes)
        $count++
    }
    Log "Extracted $count files."
    Log ''

    # --- Run Setup.ps1 ---
    $setupScript = Join-Path $extractDir 'Setup.ps1'
    if (-not (Test-Path $setupScript)) {
        Log 'ERROR: Setup.ps1 not found after extraction!'
        throw 'Setup.ps1 missing'
    }

    Log 'Launching Setup.ps1...'
    Log ''

    # Use dot-source so it runs in our scope (& would create a child scope
    # that can't show the WinForms GUI properly in some ps2exe builds).
    . $setupScript

    Log ''
    Log 'Setup finished.'
}
catch {
    Log ''
    Log "ERROR: $_"
    Log "$($_.ScriptStackTrace)"
    Log ''
    Log "Full log: $logFile"
    Write-Host ''
    Write-Host 'An error occurred. See above or check:' -ForegroundColor Red
    Write-Host "  $logFile" -ForegroundColor Yellow
    Write-Host ''
    Write-Host 'Press any key to exit...' -ForegroundColor DarkGray
    try { $null = $host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown') } catch { Start-Sleep 10 }
}
finally {
    # Cleanup extracted files
    if ($extractDir -and (Test-Path $extractDir)) {
        Log 'Cleaning up temp files...'
        Remove-Item $extractDir -Recurse -Force -ErrorAction SilentlyContinue
    }
}
'@

[void]$sb.Append($launcher)

# --- Write combined script ---
$combinedScript = Join-Path $TempBuild 'Setup-Combined.ps1'
[System.IO.File]::WriteAllText($combinedScript, $sb.ToString())

$sizeKB = (Get-Item $combinedScript).Length / 1KB
Write-Host ("  Combined script: {0:N0} KB" -f $sizeKB) -ForegroundColor DarkGray

# --- Compile ---
$exePath = Join-Path $DistDir 'Setup.exe'
Write-Host "  Compiling to .exe..." -ForegroundColor Cyan

$ps2exeArgs = @{
    inputFile    = $combinedScript
    outputFile   = $exePath
    requireAdmin = $true
    title        = 'System-Setup'
    description  = 'Windows Dev Machine Setup'
    company      = 'System-Setup'
    version      = '1.0.0.0'
    copyright    = 'MIT License'
}

Invoke-ps2exe @ps2exeArgs

if (Test-Path $exePath) {
    $sizeMB = (Get-Item $exePath).Length / 1MB
    Write-Host ""
    Write-Host "  Build successful!" -ForegroundColor Green
    Write-Host ("  Output: {0}" -f $exePath) -ForegroundColor Green
    Write-Host ("  Size:   {0:N1} MB" -f $sizeMB) -ForegroundColor Green
    Write-Host ""
    Write-Host "  Distribute this single file. Double-click to run." -ForegroundColor DarkGray
}
else {
    Write-Error "Build failed."
    exit 1
}

Remove-Item $TempBuild -Recurse -Force -ErrorAction SilentlyContinue
